### ISSUE TITLE
I cannot get the react app to run at all. 

### ISSUE THREAD

**Issue by RFSwanepoel** [Acuant/JavascriptWebSDKV11#11]
Node: v12.7.0
NPM: v6.14.2

Downloaded
Ran install 
Logs: 

$ npm install

> node-sass@4.10.0 install C:\xampp\htdocs\www\acuant-web-sdk\node_modules\node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.10.0/win32-x64-72_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.10.0/win32-x64-72_binding.node":

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g. 

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> node-sass@4.10.0 postinstall C:\xampp\htdocs\www\acuant-web-sdk\node_modules\node-sass
> node scripts/build.js

Building: C:\Program Files\nodejs\node.exe C:\xampp\htdocs\www\acuant-web-sdk\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'C:\\xampp\\htdocs\\www\\acuant-web-sdk\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library='
gyp verb cli ]
gyp info using node-gyp@3.8.0
gyp info using node@12.7.0 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\xampp\htdocs\www\acuant-web-sdk\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\xampp\htdocs\www\acuant-web-sdk\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\xampp\htdocs\www\acuant-web-sdk\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\xampp\htdocs\www\acuant-web-sdk\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\xampp\htdocs\www\acuant-web-sdk\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\xampp\htdocs\www\acuant-web-sdk\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:165:21)
gyp verb `which` failed  python2 Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\xampp\htdocs\www\acuant-web-sdk\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\xampp\htdocs\www\acuant-web-sdk\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\xampp\htdocs\www\acuant-web-sdk\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\xampp\htdocs\www\acuant-web-sdk\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\xampp\htdocs\www\acuant-web-sdk\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\xampp\htdocs\www\acuant-web-sdk\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:165:21) {
gyp verb `which` failed   stack: 'Error: not found: python2\n' +
gyp verb `which` failed     '    at getNotFoundError (C:\\xampp\\htdocs\\www\\acuant-web-sdk\\node_modules\\which\\which.js:13:12)\n' +
gyp verb `which` failed     '    at F (C:\\xampp\\htdocs\\www\\acuant-web-sdk\\node_modules\\which\\which.js:68:19)\n' +
gyp verb `which` failed     '    at E (C:\\xampp\\htdocs\\www\\acuant-web-sdk\\node_modules\\which\\which.js:80:29)\n' +
gyp verb `which` failed     '    at C:\\xampp\\htdocs\\www\\acuant-web-sdk\\node_modules\\which\\which.js:89:16\n' +
gyp verb `which` failed     '    at C:\\xampp\\htdocs\\www\\acuant-web-sdk\\node_modules\\isexe\\index.js:42:5\n' +
gyp verb `which` failed     '    at C:\\xampp\\htdocs\\www\\acuant-web-sdk\\node_modules\\isexe\\windows.js:36:5\n' +
gyp verb `which` failed     '    at FSReqCallback.oncomplete (fs.js:165:21)',
gyp verb `which` failed   code: 'ENOENT'
gyp verb `which` failed }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python C:\Users\Riaan Swanepoel\AppData\Local\Programs\Python\Python38\python.EXE
gyp ERR! configure error 
gyp ERR! stack Error: spawn C:\Users\Riaan Swanepoel\AppData\Local\Programs\Python\Python38\python.EXE EACCES
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
gyp ERR! stack     at onErrorNT (internal/child_process.js:456:16)
gyp ERR! stack     at processTicksAndRejections (internal/process/task_queues.js:77:11)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\xampp\\htdocs\\www\\acuant-web-sdk\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd C:\xampp\htdocs\www\acuant-web-sdk\node_modules\node-sass
gyp ERR! node -v v12.7.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed with error code: 1
npm WARN ajv-keywords@3.4.1 requires a peer of ajv@^6.9.1 but none is installed. You must install peer dependencies yourself.
npm WARN tsutils@3.17.1 requires a peer of typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.1 (node_modules\@typescript-eslint\typescript-estree\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.0.7 (node_modules\react-scripts\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.0.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\jest-haste-map\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.10.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.10.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by sergejs-katusenoks** [comment]
It does not work on node v12, but works on node v10. I believe it requires dependency upgrades to run on on node v12.
